apps/catalog/urls.py
# coding=utf-8

from django.conf.urls import url

from .views import ProductDetailView, ProductListView


urlpatterns = [
    url(
        r'^produtos/(?P<slug>[\w_-]+)/$',
        ProductDetailView.as_view(),
        name='product_detail'
    ),
    url(
        r'^categorias/(?P<slug>[\w_-]+)/$',
        ProductListView.as_view(),
        name='category_detail'
    ),
]

apps/checkout/urls.py
# coding=utf-8

from django.conf.urls import url

from .views import add_cartitem


urlpatterns = [
    url(
        r'^adicionar-carrinho/(?P<pk>\d+)/$', add_cartitem,
        name='add_cartitem'
    ),
]

ecommerce/urls.py
# coding=utf-8

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^', include('apps.core.urls', namespace='core')),
    url(
        r'^catalogo/',
        include('apps.catalog.urls', namespace='catalog')
    ),
    url(
        r'^contas/',
        include('apps.accounts.urls', namespace='accounts')
    ),
    url(
        r'^compras/',
        include('apps.checkout.urls', namespace='checkout')
    ),
    url(r'^admin/', include(admin.site.urls)),
    url(
        r'^media/(?P<path>.*)$',
        'django.views.static.serve',
        {
            'document_root': settings.MEDIA_ROOT,
            'show_indexes': True
        }
    ),
]

apps/catalog/models.py
# coding=utf-8

from django.db import models
from django.core.urlresolvers import reverse


class Category(models.Model):

    name = models.CharField(u'Nome', max_length=100)
    slug = models.SlugField(u'Identificador', max_length=100)

    # audit fields
    created = models.DateTimeField(
        u'Criado em', auto_now_add=True
    )
    modified = models.DateTimeField(
        u'Modificado em', auto_now=True
    )

    def get_absolute_url(self):
        return reverse(
            'catalog:category_detail', args=[self.slug]
        )

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Categoria'
        verbose_name_plural = u'Categorias'
        ordering = ['name']


class Product(models.Model):

    name = models.CharField(u'Nome', max_length=100)
    slug = models.SlugField(u'Identificador', max_length=100)
    description = models.TextField(u'Descrição', blank=True)
    category = models.ForeignKey(
        Category, verbose_name=u'Categoria',
        related_name='products'
    )
    price = models.DecimalField(
        u'Preço', decimal_places=2, max_digits=10, default=0
    )

    # audit fields
    created = models.DateTimeField(u'Criado em', auto_now_add=True)
    modified = models.DateTimeField(u'Modificado em', auto_now=True)

    def category_href(self):
        return u'<a href="{}">{}</a>'.format(
            reverse(
                'admin:catalog_category_change',
                args=[self.category_id]
            ),
            self.category.name
        )
    category_href.allow_tags = True
    category_href.short_description = u'Categoria'

    def primary_photo(self):
        return self.photos.first()

    def get_absolute_url(self):
        return reverse(
            'catalog:product_detail', args=[self.slug]
        )

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Produto'
        verbose_name_plural = u'Produtos'
        ordering = ['name']


class Photo(models.Model):

    product = models.ForeignKey(
        Product, verbose_name=u'Produto', related_name='photos'
    )
    image = models.ImageField(
        u'Imagem', upload_to='photos'
    )
    primary = models.BooleanField(u'Primária?', default=False)

    def __unicode__(self):
        return self.image.name.split('/')[-1]

    class Meta:
        verbose_name = u'Foto'
        verbose_name_plural = u'Fotos'
        ordering = ['-primary']

apps/catalog/forms.py
# coding=utf-8

from django import forms

from .models import Product


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['name', 'slug', 'category']

apps/catalog/views.py
# coding=utf-8

from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.core import exceptions
from django.views import generic

from .models import Category, Product


class ProductDetailView(generic.DetailView):

    template_name = 'catalog/product_detail.html'
    model = Product


class ProductListView(generic.ListView):

    template_name = 'catalog/category_detail.html'
    paginate_by = 9
    context_object_name = 'products'

    def category():
        doc = "The category property."
        def fget(self):
            if not hasattr(self, '_category'):
                self._category = get_object_or_404(
                    Category, slug=self.kwargs['slug']
                )
            return self._category
        return locals()
    category = property(**category())

    def get_queryset(self):
        return self.category.products.all()

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(
            **kwargs
        )
        context['category'] = self.category
        return context

apps/catalog/templates/catalog/category_detail.html
{% extends "base.html" %}

{% load thumbnail static %}

{% block main %}
<!-- page-title start -->
<!-- ================ -->
<h1 class="page-title">{{ category }}</h1>
<div class="separator-2"></div>
<!-- page-title end -->
<!-- shop items start -->
 <div class="masonry-grid-fitrows row grid-space-20">
    {% for product in products %}
    <div class="col-md-4 col-sm-6 masonry-grid-item">
        {% include "catalog/product_item.html" %}
    </div>
    {% endfor %}
</div>
<!-- shop items end -->
<div class="clearfix"></div>
{% include 'pagination.html' %}
{% endblock %}

apps/catalog/templates/catalog/load_categories.html
<ul class="dropdown-menu">
    {% for category in categories %}
    <li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
    {% endfor %}
</ul>

apps/catalog/templates/catalog/product_detail.html
{% extends "base.html" %}

{% load static %}

{% block main %}
<!-- page-title start -->
<!-- ================ -->
<h1 class="page-title margin-top-clear">{{ product }}</h1>
<!-- page-title end -->

<div class="row">
	<div class="col-md-4">

		<!-- Tab panes start-->
		<div class="tab-content clear-style">
			<div class="tab-pane active" id="product-images">
				<div class="owl-carousel content-slider-with-controls-bottom">
					<div class="overlay-container">
						<img src="{% static 'images/product-1-1.png' %}" alt="">
						<a href="{% static 'images/product-1-1.png' %}" class="popup-img overlay" title="image title"><i class="fa fa-search-plus"></i></a>
					</div>
					<div class="overlay-container">
						<img src="{% static 'images/product-1-2.png' %}" alt="">
						<a href="{% static 'images/product-1-2.png' %}" class="popup-img overlay" title="image title"><i class="fa fa-search-plus"></i></a>
					</div>
					<div class="overlay-container">
						<img src="{% static 'images/product-1-3.png' %}" alt="">
						<a href="{% static 'images/product-1-3.png' %}" class="popup-img overlay" title="image title"><i class="fa fa-search-plus"></i></a>
					</div>
				</div>
			</div>
		</div>
		<!-- Tab panes end-->
		<hr>
		<span class="price">R$ {{ product.price|floatformat:"2" }}</span>
		<div class="elements-list pull-right clearfix">
			<span><i class="fa fa-star text-default"></i><i class="fa fa-star text-default"></i><i class="fa fa-star text-default"></i><i class="fa fa-star text-default"></i><i class="fa fa-star"></i></span>
			<a href="#" class="wishlist"><i class="fa fa-heart-o pr-5"></i>Wishlist</a>
		</div>
		<div class="clearfix"></div>
		<hr>
		<div class="row">
			<form role="form">
				<div class="col-md-4">
					<div class="form-group">
						<label>Quantity</label>
						<input type="text" class="form-control" value="1">
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label>Color</label>
						<select class="form-control">
							<option>Red</option>
							<option>White</option>
							<option>Black</option>
							<option>Blue</option>
							<option>Orange</option>
						</select>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label>Size</label>
						<select class="form-control">
							<option>5.3"</option>
							<option>5.7"</option>
						</select>
					</div>
				</div>
				<div class="col-md-12">
					<input type="submit" value="Add to Cart" class="btn btn-default">
				</div>
			</form>
		</div>
	</div>

	<!-- product side start -->
	<aside class="col-md-8">
		<div class="sidebar">
			<div class="side product-item vertical-divider-left">
				<div class="tabs-style-2">
					<!-- Nav tabs -->
					<ul class="nav nav-tabs" role="tablist">
						<li class="active"><a href="#h2tab1" role="tab" data-toggle="tab"><i class="fa fa-file-text-o pr-5"></i>Description</a></li>
						<li><a href="#h2tab2" role="tab" data-toggle="tab"><i class="fa fa-files-o pr-5"></i>Specifications</a></li>
						<li><a href="#h2tab3" role="tab" data-toggle="tab"><i class="fa fa-star pr-5"></i>(3) Reviews</a></li>
					</ul>
					<!-- Tab panes -->
					<div class="tab-content padding-top-clear padding-bottom-clear">
						<div class="tab-pane fade in active" id="h2tab1">
							<h4 class="title">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</h4>
							<p>Perspiciatis necessitatibus accusamus eligendi ducimus architecto reiciendis odit officiis? Alias repellendus veritatis consectetur, aliquam laborum possimus dolorem quidem, sit saepe explicabo sint.</p>
							<h4>Nostrum, consequuntur laudantium ea suscipit minima</h4>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, consequuntur laudantium ea suscipit minima aliquid vitae possimus dolor voluptatibus autem minus alias quos praesentium debitis veniam nemo et odit dolores!</p>
							<p>Alias odio, cupiditate sed, possimus aut quasi ullam. Provident dicta, officia sunt quis doloribus sed nobis, fuga ab repudiandae. Quam atque, consequuntur non nesciunt enim dolores incidunt quis officiis voluptate est asperiores mollitia quia accusamus a nulla architecto repellendus placeat. Explicabo cum nihil, recusandae numquam repudiandae temporibus aliquid saepe ea nobis aliquam vero eaque odit doloribus tempore dicta ratione! Rerum numquam doloribus delectus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta praesentium unde perferendis beatae asperiores aspernatur vero, veritatis! Vel libero cum, culpa odio, est totam eaque, ipsam voluptates saepe, quo id!</p>
						</div>
						<div class="tab-pane fade" id="h2tab2">
							<h4 class="space-top">Specifications</h4>
							<hr>
							<dl class="dl-horizontal">
								<dt>Screen</dt>
								<dd>4.95” 1920x1080 display</dd>
								<dt>Cameras</dt>
								<dd>1.3MP front facing, 8MP rear facing with Optical Image Stabilization</dd>
								<dt>Dimensions</dt>
								<dd>69.17 x 137.84 x 8.59 mm (130g)</dd>
								<dt>Battery</dt>
								<dd>2300 mAh. Talk time up to 17 hours*. Standby time up to 300 hours†. Internet use time up to 8.5 hours on Wi-Fi, up to 7 hours on LTE‡. Wireless Charging built-in</dd>
								<dt>Audio</dt>
								<dd>Built-in speaker 3.5mm stereo audio connector</dd>
								<dt>Processing</dt>
								<dd>CPU: Qualcomm Snapdragon™ 800, 2.26GHz processor</dd>
								<dd>GPU: Adreno 330, 450MHz</dd>
								<dt>Wireless</dt>
								<dd>Dual-band Wi-Fi (2.4G/5G) 802.11 a/b/g/n/ac</dd>
							</dl>
							<hr>
						</div>
						<div class="tab-pane fade" id="h2tab3">
							<!-- comments start -->
							<div class="comments margin-clear space-top">
								<!-- comment start -->
								<div class="comment clearfix">
									<div class="comment-avatar">
										<img src="images/avatar.jpg" alt="avatar">
									</div>
									<div class="comment-content">
										<h3>Amazing!</h3>
										<div class="comment-meta"> <i class="fa fa-star text-default"></i> <i class="fa fa-star text-default"></i> <i class="fa fa-star text-default"></i> <i class="fa fa-star text-default"></i> <i class="fa fa-star"></i> | Today, 12:31</div>
										<div class="comment-body clearfix">
											<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo </p>
											<a href="blog-post.html" class="btn btn-gray more pull-right"><i class="fa fa-reply"></i> Reply</a>
										</div>
									</div>

								</div>
								<!-- comment end -->

								<!-- comment start -->
								<div class="comment clearfix">
									<div class="comment-avatar">
										<img src="images/avatar.jpg" alt="avatar">
									</div>
									<div class="comment-content clearfix">
										<h3>Works Perfect!</h3>
										<div class="comment-meta"> <i class="fa fa-star text-default"></i> <i class="fa fa-star text-default"></i> <i class="fa fa-star text-default"></i> <i class="fa fa-star text-default"></i> <i class="fa fa-star text-default"></i> | Oct 15</div>
										<div class="comment-body">
											<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo </p>
											<a href="blog-post.html" class="btn btn-gray more pull-right"><i class="fa fa-reply"></i> Reply</a>
										</div>
									</div>
								</div>
								<!-- comment end -->

								<!-- comment start -->
								<div class="comment clearfix">
									<div class="comment-avatar">
										<img src="images/avatar.jpg" alt="avatar">
									</div>
									<div class="comment-content clearfix">
										<h3>Worth to Buy</h3>
										<div class="comment-meta"> <i class="fa fa-star text-default"></i> <i class="fa fa-star text-default"></i> <i class="fa fa-star text-default"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> | Sep 25</div>
										<div class="comment-body">
											<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo </p>
											<a href="blog-post.html" class="btn btn-gray more pull-right"><i class="fa fa-reply"></i> Reply</a>
										</div>
									</div>
								</div>
								<!-- comment end -->

							</div>
							<!-- comments end -->

							<!-- comments form start -->
							<div class="comments-form">
								<h2 class="title">Add your Review</h2>
								<form role="form" id="comment-form">
									<div class="form-group has-feedback">
										<label for="name4">Name</label>
										<input type="text" class="form-control" id="name4" placeholder="" name="name4" required="">
										<i class="fa fa-user form-control-feedback"></i>
									</div>
									<div class="form-group has-feedback">
										<label for="subject4">Subject</label>
										<input type="text" class="form-control" id="subject4" placeholder="" name="subject4" required="">
										<i class="fa fa-pencil form-control-feedback"></i>
									</div>
									<div class="form-group">
										<label>Rating</label>
										<select class="form-control" id="review">
											<option value="five">5</option>
											<option value="four">4</option>
											<option value="three">3</option>
											<option value="two">2</option>
											<option value="one">1</option>
										</select>
									</div>
									<div class="form-group has-feedback">
										<label for="message4">Message</label>
										<textarea class="form-control" rows="8" id="message4" placeholder="" name="message4" required=""></textarea>
										<i class="fa fa-envelope-o form-control-feedback"></i>
									</div>
									<input type="submit" value="Submit" class="btn btn-default">
								</form>
							</div>
							<!-- comments form end -->
						</div>
					</div>
				</div>
			</div>
		</div>
	</aside>
<!-- product side end -->
</div>
{% endblock %}

apps/catalog/templates/catalog/product_item.html
{% load thumbnail static %}
<div class="listing-item">
    <div class="overlay-container">
        {% if product.primary_photo %}
        <img src="{{ product.primary_photo.image|thumbnail_url:'product_photo' }}" alt="">
        {% else %}
        <img src="{% static 'images/product-2.png' %}" alt="">
        {% endif %}
        <a href="{{ product.get_absolute_url }}" class="overlay small">
            <i class="fa fa-plus"></i>
            <span>Detalhes</span>
        </a>
    </div>
    <div class="listing-item-body clearfix">
        <h3 class="title"><a href="{{ product.get_absolute_url }}">{{ product }}</a></h3>
        <p>{{ product }}</p>
        <span class="price">R$ {{ product.price|floatformat:"2" }}</span>
        <div class="elements-list pull-right">
            <a href="{% url 'checkout:add_cartitem' product.pk %}"><i class="fa fa-shopping-cart pr-10"></i>Adicionar ao carrinho</a>
        </div>
    </div>
</div>