apps/accounts/urls.py
# coding=utf-8

from django.conf.urls import url

from .views import index, password_change


urlpatterns = [
    url(
        r'^entrar/', 'django.contrib.auth.views.login',
        {'template_name': 'accounts/login.html'},
        name='login'
    ),
    url(
        r'^sair/', 'django.contrib.auth.views.logout',
        {'next_page': 'core:index'},
        name='logout'
    ),
    url(r'^$', index, name='index'),
    url(
        r'^alterar-senha/$', password_change, 
        name='password_change'
    ),
]

apps/core/urls.py
# coding=utf-8

from django.conf.urls import url

from .views import about, contact, index


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^sobre/$', about, name='about'),
    # url(
    #     r'^$', render_template,
    #     {'template_name': 'index.html'}, name='index'
    # ),
    # url(
    #     r'^sobre/$', render_template,
    #     {'template_name': 'about.html'}, name='about'
    # ),
    url(r'^contato/$', contact, name='contact'),
]

ecommerce/urls.py
# coding=utf-8

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^', include('apps.core.urls', namespace='core')),
    url(
        r'^catalogo/',
        include('apps.catalog.urls', namespace='catalog')
    ),
    url(
        r'^contas/',
        include('apps.accounts.urls', namespace='accounts')
    ),
    url(
        r'^compras/',
        include('apps.checkout.urls', namespace='checkout')
    ),
    url(r'^admin/', include(admin.site.urls)),
    url(
        r'^media/(?P<path>.*)$',
        'django.views.static.serve',
        {
            'document_root': settings.MEDIA_ROOT,
            'show_indexes': True
        }
    ),
]

apps/core/models.py
# coding=utf-8

from django.db import models
from django.conf import settings

from ecommerce.utils.mail import send_mail_template


class Contact(models.Model):

    name = models.CharField(u'Nome', max_length=50)
    email = models.EmailField(u'E-mail')
    subject = models.CharField(u'Assunto', max_length=100)
    message = models.TextField(u'Mensagem')

    created = models.DateTimeField(
        u'Criado em', auto_now_add=True
    )

    def send_mail(self):
        context_email = {
            'message': self.message, 'name': self.name,
            'email': self.email, 'date': self.created
        }
        send_mail_template(
            self.subject, [settings.CONTACT_EMAIL],
            'contact_email.html', context_email
        )

    def __unicode__(self):
        return self.subject

    class Meta:
        verbose_name = u'Contato'
        verbose_name_plural = u'Contatos'


def contact_post_save(**kwargs):
    contact = kwargs['instance']
    contact.send_mail()

models.signals.post_save.connect(
    contact_post_save, sender=Contact
)

apps/core/forms.py
# coding=utf-8

from django import forms

from .models import Contact


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']

apps/core/views.py
# coding=utf-8

from django.shortcuts import render, get_object_or_404
from django.conf import settings
from django.views import generic
from django.http import Http404

from ecommerce.utils.mail import send_mail_template

from apps.catalog.models import Product, Category

from .models import Contact
from .forms import ContactForm


class IndexView(generic.ListView):

    def get_paginate_by(self, queryset):
        return self.request.GET.get('paginate_by', 3)

    def get_queryset(self):
        pk = self.request.GET.get('category')
        try:
            category = Category.objects.get(pk=pk)
        except:
            category = None
        if category:
            return category.products.all()
        else:
            return Product.objects.all()

    def get_template_names(self):
        if self.request.is_ajax():
            return ['_index.html']
        else:
            return ['index.html']


index = IndexView.as_view()


def about(request):
    context = {}
    return render(request, 'about.html', context)

def contact(request):
    context = {}
    form = ContactForm(request.POST or None)
    if form.is_valid():
        contact = form.save()
        context['success'] = True
    context['form'] = form
    return render(request, 'contact.html', context)

apps/core/templates/_index.html
{% for product in object_list %}
<div class="col-md-4 col-sm-6 masonry-grid-item">
    {% include 'catalog/product_item.html' %}
</div>
{% endfor %}

apps/core/templates/about.html
{% extends "base.html" %}

{% block title %}Sobre a Empresa{% endblock %}

{% block breadcrumb %}
{{ block.super }}
<li><i class="fa pr-10"></i><a href="">Sobre</a></li>
{% endblock %}

{% block main %}
<h1 class="page-title">Sobre</h1>
<div class="separator-2"></div>
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas nulla suscipit <br class="hidden-sm hidden-xs"> unde rerum mollitia dolorum.</p>
{% endblock %}

apps/core/templates/base.html
<!DOCTYPE html>
{% load static categories %}
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
	<head>
		<meta charset="utf-8">
		<title>{% block title %}E-Commerce{% endblock %}</title>
		<meta name="description" content="iDea a Bootstrap-based, Responsive HTML5 Template">
		<meta name="author" content="htmlcoder.me">
		<!-- Mobile Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- Favicon -->
		<link rel="shortcut icon" href="images/favicon.ico">
		<!-- Web Fonts -->
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700,300&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=PT+Serif' rel='stylesheet' type='text/css'>

		<!-- Bootstrap core CSS -->
		<link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">

		<!-- Font Awesome CSS -->
		<link href="{% static 'fonts/font-awesome/css/font-awesome.css' %}" rel="stylesheet">

		<!-- Fontello CSS -->
		<link href="{% static 'fonts/fontello/css/fontello.css' %}" rel="stylesheet">

		<!-- owl carousel CSS file -->
		<link href="{% static 'plugins/owl-carousel/owl.carousel.css' %}" rel="stylesheet">

		<!-- iDea core CSS file -->
		<link href="{% static 'css/style.css' %}" rel="stylesheet">

		<!-- Color Scheme (In order to change the color scheme, replace the red.css with the color scheme that you prefer)-->
		<link href="{% static 'css/skins/red.css' %}" rel="stylesheet">

		<!-- Custom css -->
		<link href="{% static 'css/custom.css' %}" rel="stylesheet">

		{% block css %}{% endblock %}
	</head>
	<body>
		<!-- scrollToTop -->
		<!-- ================ -->
		<div class="scrollToTop"><i class="icon-up-open-big"></i></div>

		<!-- page wrapper start -->
		<!-- ================ -->
		<div class="page-wrapper">

			<!-- header-top start -->
			<!-- ================ -->
			<div class="header-top">
				<div class="container">
					<div class="row">
						<div class="col-xs-10">
							<!-- header-top-second start -->
							<!-- ================ -->
							<div id="header-top-second"  class="clearfix">
								<!-- header top dropdowns start -->
								<!-- ================ -->
								<div class="header-top-dropdown">
									<div class="btn-group dropdown">
										<a href="#" class="btn dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i> Pesquisar</a>
										<ul class="dropdown-menu dropdown-menu-right dropdown-animation">
											<li>
												<form role="search" class="search-box">
													<div class="form-group has-feedback">
														<input type="text" class="form-control" placeholder="Pesquisar">
														<i class="fa fa-search form-control-feedback"></i>
													</div>
												</form>
											</li>
										</ul>
									</div>
									<div class="btn-group dropdown">
										<a href="" class="btn dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i> Carrinho ({{ cart_items.count }})</a>
										<ul class="dropdown-menu dropdown-menu-right dropdown-animation cart">
											<li>
												<table class="table table-hover">
													<thead>
														<tr>
															<th class="quantity">QT</th>
															<th class="product">Produto</th>
															<th class="amount">Subtotal</th>
														</tr>
													</thead>
													<tbody>
														{% for item in cart_items %}
														<tr>
															<td class="quantity">{{ item.quantity }} x</td>
															<td class="product"><a href="{{ item.product.get_absolute_url }}">{{ item.product }}</a></td>
															<td class="amount">R$ {{ item.product.price|floatformat:"2" }}</td>
														</tr>
														{% endfor %}
													</tbody>
												</table>
												<div class="panel-body text-right">
													<a href="" class="btn btn-group btn-default btn-sm">Ver Carrinho</a>
													<a href="" class="btn btn-group btn-default btn-sm">Finalizar</a>
												</div>
											</li>
										</ul>
									</div>
									{% if user.is_authenticated %}
									<div class="btn-group">
										<a href="{% url 'accounts:index' %}" class="btn"><i class="fa fa-user"></i> Conta</a>
									</div>
									<div class="btn-group">
										<a href="{% url 'accounts:logout' %}" class="btn"><i class="fa fa-user"></i> Sair</a>
									</div>
									{% else %}
									<div class="btn-group">
										<a href="{% url 'accounts:login' %}" class="btn"><i class="fa fa-user"></i> Entrar</a>
									</div>
									{% endif %}
								</div>
								<!--  header top dropdowns end -->

							</div>
							<!-- header-top-second end -->

						</div>
					</div>
				</div>
			</div>
			<!-- header-top end -->

			<!-- header start (remove fixed class from header in order to disable fixed navigation mode) -->
			<!-- ================ -->
			<header class="header fixed clearfix">
				<div class="container">
					<div class="row">
						<div class="col-md-3">

							<!-- header-left start -->
							<!-- ================ -->
							<div class="header-left clearfix">

								<!-- logo -->
								<div class="logo">
									<a href="{% url 'core:index' %}"><img id="logo" src="{% static 'images/logo_red.png' %}" alt="Locus Ecommerce"></a>
								</div>

								<!-- name-and-slogan -->
								<div class="site-slogan">
									Locus Ecommerce
								</div>

							</div>
							<!-- header-left end -->

						</div>
						<div class="col-md-9">

							<!-- header-right start -->
							<!-- ================ -->
							<div class="header-right clearfix">

								<!-- main-navigation start -->
								<!-- ================ -->
								<div class="main-navigation animated">

									<!-- navbar start -->
									<!-- ================ -->
									<nav class="navbar navbar-default" role="navigation">
										<div class="container-fluid">
											<!-- Toggle get grouped for better mobile display -->
											<div class="navbar-header">
												<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
													<span class="sr-only">Toggle navigation</span>
													<span class="icon-bar"></span>
													<span class="icon-bar"></span>
													<span class="icon-bar"></span>
												</button>
											</div>

											<!-- Collect the nav links, forms, and other content for toggling -->
											<div class="collapse navbar-collapse" id="navbar-collapse-1">
												<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="{% url 'core:index' %}">Início</a>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Categorias</a>
							<ul class="dropdown-menu">
							    {% for category in categories %}
							    <li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
							    {% endfor %}
							</ul>
						</li>
						<li class="dropdown">
							<a href="{% url 'core:about' %}" class="dropdown-toggle" data-toggle="dropdown">Sobre</a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'core:about' %}">Sobre a Empresa</a></li>
								<li><a href="{% url 'core:contact' %}">Contato</a></li>
							</ul>
						</li>
												</ul>
											</div>
										</div>
									</nav>
									<!-- navbar end -->
								</div>
								<!-- main-navigation end -->
							</div>
							<!-- header-right end -->
						</div>
					</div>
				</div>
			</header>
			<!-- header end -->

			<!-- page-intro start-->
			<!-- ================ -->
			<div class="page-intro">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<ol class="breadcrumb">
                                {% block breadcrumb %}
								<li><i class="fa fa-home pr-10"></i><a href="">Início</a></li>
                                {% endblock %}
							</ol>
						</div>
					</div>
				</div>
			</div>
			<!-- page-intro end -->

			<!-- main-container start -->
			<!-- ================ -->
			<section class="main-container">

				<div class="container">
					<div class="row">

						<!-- main start -->
                        <div class="main col-md-12">
							{% for message in messages %}
							<div class="alert alert-{{ message.tags }}">
								{{ message }}
							</div>
							{% endfor %}
                            {% block main %}{% endblock %}
                        </div>
						<!-- main end -->

					</div>
				</div>
			</section>
			<!-- main-container end -->

			<!-- footer start (Add "light" class to #footer in order to enable light footer) -->
			<!-- ================ -->
			<footer id="footer">
				<!-- .subfooter start -->
				<!-- ================ -->
				<div class="subfooter">
					<div class="container">
						<div class="row">
							<div class="col-md-6">
								<p>Copyright © 2014 iDea by <a target="_blank" href="http://htmlcoder.me">HtmlCoder</a>. All Rights Reserved</p>
							</div>
							<div class="col-md-6">
								<nav class="navbar navbar-default" role="navigation">
									<!-- Toggle get grouped for better mobile display -->
									<div class="navbar-header">
										<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-2">
											<span class="sr-only">Toggle navigation</span>
											<span class="icon-bar"></span>
											<span class="icon-bar"></span>
											<span class="icon-bar"></span>
										</button>
									</div>
									<div class="collapse navbar-collapse" id="navbar-collapse-2">
										<ul class="nav navbar-nav">
											<li><a href="index.html">Home</a></li>
											<li><a href="page-about.html">About</a></li>
											<li><a href="blog-right-sidebar.html">Blog</a></li>
											<li><a href="portfolio-3col.html">Portfolio</a></li>
											<li><a href="page-contact.html">Contact</a></li>
										</ul>
									</div>
								</nav>
							</div>
						</div>
					</div>
				</div>
				<!-- .subfooter end -->

			</footer>
			<!-- footer end -->

		</div>
		<!-- page-wrapper end -->
		<!-- Jquery and Bootstap core js files -->
		<script type="text/javascript" src="{% static 'plugins/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
		<!-- Modernizr javascript -->
		<script type="text/javascript" src="{% static 'plugins/modernizr.js' %}"></script>
		<!-- Owl carousel javascript -->
		<script type="text/javascript" src="{% static 'plugins/owl-carousel/owl.carousel.js' %}"></script>
		<!-- Custom Scripts -->
		<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
		{% block javascript %}{% endblock %}
	</body>
</html>

apps/core/templates/contact.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block main %}
<!-- page-title start -->
<h1 class="page-title">Contato</h1>
<!-- page-title end -->
<div class="contact-form">
    {% if success %}
    <div class="alert alert-success" id="contactSuccess">
		<strong>Sucesso!</strong> Sua mensagem foi enviada para nós.
	</div>
    {% else %}
    <form id="contact-form" role="form" action="" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group has-feedback{% if field.errors %} has-error{% endif %}">
            <label class="control-label" for="{{ field.auto_id }}">{{ field.label }}</label>
            {% render_field field class="form-control" %}
            <i class="fa fa-user form-control-feedback"></i>
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
        {% endfor %}
        <input type="submit" value="Submit" class="btn btn-default">
    </form>
    {% endif %}
</div>
</div>
{% endblock %}

apps/core/templates/contact_email.html
Nome: {{ name }}
E-mail: {{ email }}
Data: {{ date|date:'d \d\e M \d\e Y'|default:"não informada" }}
{{ message }}

apps/core/templates/index.html
{% extends "base.html" %}

{% load thumbnail static categories %}

{% block javascript %}
<script type="text/javascript">
    $(function(){
        $("#form-filter").on("submit", function(event){
            var $form = $(this);
            var data = $form.serialize();
            var url = "{% url 'core:index' %}";
            $.ajax({
                url: url,
                data: data,
                type: 'get',
                success: function(response){
                    $("#list-products").html(response);
                }
            });
            return false;
        });
    });
</script>
{% endblock %}

{% block main %}
<!-- page-title start -->
<!-- ================ -->
<h1 class="page-title">Shop</h1>
<div class="separator-2"></div>
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas nulla suscipit <br class="hidden-sm hidden-xs"> unde rerum mollitia dolorum.</p>
<!-- page-title end -->

<div class="sorting-filters">
    <form class="form-inline" id="form-filter">
        {% get_categories as categories %}
        <div class="form-group">
            <label>Categorias</label>
            <select class="form-control" name="category">
                <option value="">------------</option>
                {% for category in categories %}
                <option value="{{ category.pk }}">{{ category }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </form>
</div>

<!-- shop items start -->
 <div id="list-products" class="masonry-grid-fitrows row grid-space-20">
     {% include "_index.html" %}
</div>
<!-- shop items end -->
<div class="clearfix"></div>
{% include 'pagination.html' %}
{% endblock %}

apps/core/templates/pagination.html
{% load utils %}
<!-- pagination start -->
<ul class="pagination">
    {% if page_obj.has_previous %}
    <li><a href="?{{ request.GET|remove_and_encode:'page' }}&page={{ page_obj.previous_page_number }}">«</a></li>
    {% endif %}
    {% for page_number in paginator.page_range %}
        {% if page_number == page_obj.number %}
        <li class="active"><a href="?{{ request.GET|remove_and_encode:'page' }}&page={{ page_obj.number }}">{{ page_obj.number }} <span class="sr-only">(current)</span></a></li>
        {% else %}
        <li><a href="?{{ request.GET|remove_and_encode:'page' }}&page={{ page_number }}">{{ page_number }}</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li><a href="?{{ request.GET|remove_and_encode:'page' }}&page={{ page_obj.next_page_number }}">»</a></li>
    {% endif %}
</ul>
<!-- pagination end -->